= Local Context Vocabularies and Ontology

This repository contains https://localcontexts.org[Local Context] labels as Semantic Web vocabularies, as used by the https://mspgh.unimelb.edu.au/centres-institutes/centre-for-health-equity/research-group/indigenous-data-network[Indigenous Data Network (IDN)].

The IDN applies Local Context labels and to datasets related to Indigenous people to improve dataset metadata and, ultimately, improved Indigenous data governance. The 'things' we are targetting with these vocabularies and ontology are catalogued according to the https://data.idnau.org/pid/cp[Indigenous Data Network Catalogue Profile], but Local Context metadata can be applied in other cataloguing profiles and standards.

The two label vocabularies, _Traditional Knowledge Labels_ (TK) and _Biocultural Labels_ (BC) are online with persistent web identifiers:

* **https://data.idnau.org/pid/vocab/tk-labels**
* **https://data.idnau.org/pid/vocab/bc-labels**

The labels are linked, where relevant, to _Local Context Notices_, which are online with persistent web identifiers:

* **https://data.idnau.org/pid/vocab/lc-notices**

The Labels, Notices and supporting classes and properties are defined in the _Local Context Labels Extension Vocabulary_:

* **https://data.idnau.org/pid/lc-ont#**

== License & Rights

The contents of this repository is licensed under Creative Commons 4.0 International. See the LICENSE file in the repository for details. Note that the underlying content of the Local Context labels has the following copyright statement at https://localcontexts.org:

_All Labels and Notices Icons and Template Texts © 2010 - 2026 Local Contexts. All Rights Reserved._



== Contacts

For technical enquiries:

**Jamie Feiss** +
*Data Infrastructure Developer* +
Indigenous Data Network +
University of Melbourne +
jamie.feiss@unimelb.edu.au

For policy:

**Les Kneebone** +
*Vocabulary Specialist* +
KurrawongAI
les@kurrawong.ai
